// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpPKzZ1oA7tJiZEYNdpuEN6-RFEd1wNi4',
    appId: '1:585519584298:web:294048728471f3f72e1f53',
    messagingSenderId: '585519584298',
    projectId: 'quickgriev',
    authDomain: 'quickgriev.firebaseapp.com',
    storageBucket: 'quickgriev.firebasestorage.app',
    measurementId: 'G-G71DK7646F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaryTng2HztORKoDnzEd_s_SHq2lTi2M8',
    appId: '1:585519584298:android:17ce2d60a9ceb2222e1f53',
    messagingSenderId: '585519584298',
    projectId: 'quickgriev',
    storageBucket: 'quickgriev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIlhtxOa_nJoT7Ze7Fy1V_V-sstYAbbPg',
    appId: '1:585519584298:ios:9173cf9c09f705452e1f53',
    messagingSenderId: '585519584298',
    projectId: 'quickgriev',
    storageBucket: 'quickgriev.firebasestorage.app',
    iosBundleId: 'com.example.quickGriev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIlhtxOa_nJoT7Ze7Fy1V_V-sstYAbbPg',
    appId: '1:585519584298:ios:9173cf9c09f705452e1f53',
    messagingSenderId: '585519584298',
    projectId: 'quickgriev',
    storageBucket: 'quickgriev.firebasestorage.app',
    iosBundleId: 'com.example.quickGriev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpPKzZ1oA7tJiZEYNdpuEN6-RFEd1wNi4',
    appId: '1:585519584298:web:e5377d9957aba8132e1f53',
    messagingSenderId: '585519584298',
    projectId: 'quickgriev',
    authDomain: 'quickgriev.firebaseapp.com',
    storageBucket: 'quickgriev.firebasestorage.app',
    measurementId: 'G-1PNQH3N3V3',
  );
}
